-- ============================================================
-- EngClinica Pro
-- Migration: 024_calibracao_execucoes.sql
-- Objetivo:
-- - Criar execucoes concretas de calibracao com snapshot auditavel
-- - Registrar leituras brutas, calculos e orcamento de incerteza
-- - Preparar certificados PDF privados e fechamento imutavel
-- ============================================================

create table if not exists public.calibracao_execucoes (
  id uuid primary key default gen_random_uuid(),
  organizacao_id uuid not null references public.organizacoes(id) on delete restrict,
  numero_certificado bigint generated by default as identity unique,
  empresa_id uuid not null references public.empresas(id) on delete restrict,
  equipamento_id uuid not null references public.equipamentos(id) on delete restrict,
  procedimento_id uuid not null references public.calibracao_procedimentos(id) on delete restrict,
  procedimento_nome_snapshot text not null,
  procedimento_versao_snapshot integer not null,
  norma_utilizada_snapshot text null,
  local_calibracao text null,
  temperatura_ambiente numeric(18,8) null,
  incerteza_temperatura numeric(18,8) null,
  unidade_temperatura text null default '°C',
  umidade_relativa numeric(18,8) null,
  incerteza_umidade numeric(18,8) null,
  unidade_umidade text null default '%',
  pressao_atmosferica numeric(18,8) null,
  incerteza_pressao numeric(18,8) null,
  unidade_pressao text null default 'kPa',
  observacoes text null,
  data_calibracao date not null,
  data_emissao date not null default current_date,
  data_validade date null,
  tecnico_executor_nome text not null,
  tecnico_executor_registro text null,
  responsavel_tecnico_nome text not null,
  responsavel_tecnico_registro text null,
  responsavel_solicitante text null,
  status text not null default 'rascunho',
  criterio_conformidade_aplicado boolean not null default false,
  regra_decisao text null,
  resultado_geral text null,
  os_id uuid null references public.ordens_servico(id) on delete set null,
  pdf_storage_path text null,
  pdf_hash text null,
  fechado_em timestamp with time zone null,
  ativo boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  created_by uuid null references public.usuarios(id) on delete set null,
  updated_by uuid null references public.usuarios(id) on delete set null,
  constraint calibracao_execucoes_status_check
    check (status in ('rascunho', 'em_execucao', 'fechada', 'cancelada')),
  constraint calibracao_execucoes_resultado_check
    check (
      resultado_geral is null
      or resultado_geral in ('conforme', 'nao_conforme', 'sem_declaracao_conformidade')
    ),
  constraint calibracao_execucoes_datas_check
    check (data_validade is null or data_validade >= data_calibracao),
  constraint calibracao_execucoes_regra_decisao_check
    check (not criterio_conformidade_aplicado or length(trim(coalesce(regra_decisao, ''))) > 0)
);

create table if not exists public.calibracao_execucao_tabelas (
  id uuid primary key default gen_random_uuid(),
  organizacao_id uuid not null references public.organizacoes(id) on delete restrict,
  execucao_id uuid not null references public.calibracao_execucoes(id) on delete cascade,
  procedimento_tabela_id uuid null references public.calibracao_procedimento_tabelas(id) on delete set null,
  nome_snapshot text not null,
  grandeza_snapshot text not null,
  unidade_snapshot text not null,
  quantidade_leituras_snapshot integer not null default 1,
  padrao_id uuid null references public.calibracao_padroes(id) on delete set null,
  padrao_tabela_id uuid null references public.calibracao_padrao_tabelas(id) on delete set null,
  padrao_nome_snapshot text null,
  padrao_numero_certificado_snapshot text null,
  padrao_validade_snapshot date null,
  padrao_identificacao_snapshot text null,
  padrao_laboratorio_snapshot text null,
  resolucao_padrao_snapshot numeric(18,8) null,
  resolucao_equipamento_snapshot numeric(18,8) null,
  fator_confiabilidade_modo_snapshot text not null default 'calcular_95',
  fator_k_fixo_snapshot numeric(18,8) null,
  incluir_criterio_aceitacao_snapshot boolean not null default false,
  criterio_aceitacao_tipo_snapshot text null,
  criterio_aceitacao_valor_maximo_snapshot numeric(18,8) null,
  criterio_aceitacao_valor_minimo_snapshot numeric(18,8) null,
  corrigir_erro_sistematico_snapshot boolean not null default false,
  ordem integer not null default 0,
  created_at timestamp with time zone not null default now(),
  constraint calibracao_execucao_tabelas_qtd_leituras_check check (quantidade_leituras_snapshot >= 1),
  constraint calibracao_execucao_tabelas_fator_modo_check
    check (fator_confiabilidade_modo_snapshot in ('calcular_95', 'k_fixo', 'manual_execucao')),
  constraint calibracao_execucao_tabelas_criterio_tipo_check
    check (
      criterio_aceitacao_tipo_snapshot is null
      or criterio_aceitacao_tipo_snapshot in ('absoluto', 'percentual', 'faixa')
    )
);

create table if not exists public.calibracao_execucao_pontos (
  id uuid primary key default gen_random_uuid(),
  organizacao_id uuid not null references public.organizacoes(id) on delete restrict,
  execucao_tabela_id uuid not null references public.calibracao_execucao_tabelas(id) on delete cascade,
  procedimento_ponto_id uuid null references public.calibracao_procedimento_pontos(id) on delete set null,
  ordem integer not null default 0,
  valor_nominal numeric(18,8) not null,
  media_valores_medidos numeric(18,8) null,
  desvio_padrao_amostral numeric(18,12) null,
  incerteza_tipo_a numeric(18,12) null,
  tendencia_bruta numeric(18,12) null,
  correcao_padrao numeric(18,12) null,
  tendencia_corrigida numeric(18,12) null,
  incerteza_padrao_certificado numeric(18,12) null,
  incerteza_padrao_convertida numeric(18,12) null,
  incerteza_resolucao_equipamento numeric(18,12) null,
  incerteza_resolucao_padrao numeric(18,12) null,
  incerteza_combinada numeric(18,12) null,
  graus_liberdade_efetivos_veff numeric(18,8) null,
  veff_infinito boolean not null default false,
  fator_abrangencia_k numeric(18,8) null,
  incerteza_expandida numeric(18,12) null,
  criterio_aceitacao_valor numeric(18,8) null,
  resultado_conformidade text null,
  observacoes text null,
  calculado_em timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint calibracao_execucao_pontos_resultado_check
    check (resultado_conformidade is null or resultado_conformidade in ('conforme', 'nao_conforme', 'sem_criterio'))
);

create table if not exists public.calibracao_execucao_leituras (
  id uuid primary key default gen_random_uuid(),
  organizacao_id uuid not null references public.organizacoes(id) on delete restrict,
  execucao_ponto_id uuid not null references public.calibracao_execucao_pontos(id) on delete cascade,
  ordem integer not null,
  valor_medido numeric(18,8) not null,
  created_at timestamp with time zone not null default now(),
  constraint calibracao_execucao_leituras_ordem_check check (ordem >= 1)
);

create table if not exists public.calibracao_execucao_componentes_incerteza (
  id uuid primary key default gen_random_uuid(),
  organizacao_id uuid not null references public.organizacoes(id) on delete restrict,
  execucao_ponto_id uuid not null references public.calibracao_execucao_pontos(id) on delete cascade,
  nome text not null,
  categoria text not null,
  distribuicao text null,
  valor_origem numeric(18,12) null,
  divisor numeric(18,12) null,
  coeficiente_sensibilidade numeric(18,12) not null default 1,
  incerteza_padrao numeric(18,12) not null,
  graus_liberdade numeric(18,8) null,
  graus_liberdade_infinito boolean not null default false,
  origem text null,
  ordem integer not null default 0,
  created_at timestamp with time zone not null default now(),
  constraint calibracao_execucao_componentes_categoria_check check (categoria in ('tipo_a', 'tipo_b')),
  constraint calibracao_execucao_componentes_distribuicao_check
    check (distribuicao is null or distribuicao in ('normal', 'retangular', 'triangular', 't_student', 'outra'))
);

create index if not exists idx_calibracao_execucoes_organizacao on public.calibracao_execucoes (organizacao_id);
create index if not exists idx_calibracao_execucoes_empresa on public.calibracao_execucoes (empresa_id);
create index if not exists idx_calibracao_execucoes_equipamento on public.calibracao_execucoes (equipamento_id);
create index if not exists idx_calibracao_execucoes_procedimento on public.calibracao_execucoes (procedimento_id);
create index if not exists idx_calibracao_execucoes_data on public.calibracao_execucoes (data_calibracao);
create index if not exists idx_calibracao_execucoes_status on public.calibracao_execucoes (status);
create index if not exists idx_calibracao_execucao_tabelas_execucao on public.calibracao_execucao_tabelas (execucao_id);
create index if not exists idx_calibracao_execucao_pontos_tabela on public.calibracao_execucao_pontos (execucao_tabela_id);
create index if not exists idx_calibracao_execucao_leituras_ponto on public.calibracao_execucao_leituras (execucao_ponto_id);
create index if not exists idx_calibracao_execucao_componentes_ponto on public.calibracao_execucao_componentes_incerteza (execucao_ponto_id);

drop trigger if exists trg_calibracao_execucoes_updated_at on public.calibracao_execucoes;
create trigger trg_calibracao_execucoes_updated_at before update on public.calibracao_execucoes
for each row execute function public.set_updated_at();

drop trigger if exists trg_calibracao_execucao_pontos_updated_at on public.calibracao_execucao_pontos;
create trigger trg_calibracao_execucao_pontos_updated_at before update on public.calibracao_execucao_pontos
for each row execute function public.set_updated_at();

insert into storage.buckets (id, name, public)
values ('calibracao-certificados', 'calibracao-certificados', false)
on conflict (id) do nothing;

alter table public.calibracao_execucoes enable row level security;
alter table public.calibracao_execucao_tabelas enable row level security;
alter table public.calibracao_execucao_pontos enable row level security;
alter table public.calibracao_execucao_leituras enable row level security;
alter table public.calibracao_execucao_componentes_incerteza enable row level security;

drop policy if exists "calibracao_execucoes_select_mesma_organizacao" on public.calibracao_execucoes;
create policy "calibracao_execucoes_select_mesma_organizacao" on public.calibracao_execucoes
for select to authenticated using (organizacao_id = public.current_organizacao_id());

drop policy if exists "calibracao_execucoes_insert_admin_gestor_tecnico" on public.calibracao_execucoes;
create policy "calibracao_execucoes_insert_admin_gestor_tecnico" on public.calibracao_execucoes
for insert to authenticated with check (
  organizacao_id = public.current_organizacao_id()
  and status = 'rascunho'
  and os_id is null
  and pdf_storage_path is null
  and pdf_hash is null
  and fechado_em is null
  and exists (
    select 1
    from public.empresas e
    where e.id = calibracao_execucoes.empresa_id
      and e.organizacao_id = public.current_organizacao_id()
  )
  and exists (
    select 1
    from public.equipamentos e
    where e.id = calibracao_execucoes.equipamento_id
      and e.empresa_id = calibracao_execucoes.empresa_id
      and e.organizacao_id = public.current_organizacao_id()
  )
  and exists (
    select 1
    from public.calibracao_procedimentos p
    where p.id = calibracao_execucoes.procedimento_id
      and p.organizacao_id = public.current_organizacao_id()
  )
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
);

drop policy if exists "calibracao_execucoes_update_admin_gestor_tecnico" on public.calibracao_execucoes;
create policy "calibracao_execucoes_update_admin_gestor_tecnico" on public.calibracao_execucoes
for update to authenticated using (
  organizacao_id = public.current_organizacao_id()
  and status not in ('fechada', 'cancelada')
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
) with check (
  organizacao_id = public.current_organizacao_id()
  and status in ('rascunho', 'em_execucao', 'cancelada')
  and os_id is null
  and pdf_storage_path is null
  and pdf_hash is null
  and fechado_em is null
  and exists (
    select 1
    from public.empresas e
    where e.id = calibracao_execucoes.empresa_id
      and e.organizacao_id = public.current_organizacao_id()
  )
  and exists (
    select 1
    from public.equipamentos e
    where e.id = calibracao_execucoes.equipamento_id
      and e.empresa_id = calibracao_execucoes.empresa_id
      and e.organizacao_id = public.current_organizacao_id()
  )
  and exists (
    select 1
    from public.calibracao_procedimentos p
    where p.id = calibracao_execucoes.procedimento_id
      and p.organizacao_id = public.current_organizacao_id()
  )
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
);

drop policy if exists "calibracao_execucao_tabelas_select_mesma_organizacao" on public.calibracao_execucao_tabelas;
create policy "calibracao_execucao_tabelas_select_mesma_organizacao" on public.calibracao_execucao_tabelas
for select to authenticated using (
  organizacao_id = public.current_organizacao_id()
  and exists (select 1 from public.calibracao_execucoes e where e.id = execucao_id and e.organizacao_id = public.current_organizacao_id())
);
drop policy if exists "calibracao_execucao_tabelas_insert_editavel" on public.calibracao_execucao_tabelas;
create policy "calibracao_execucao_tabelas_insert_editavel" on public.calibracao_execucao_tabelas
for insert to authenticated with check (
  organizacao_id = public.current_organizacao_id()
  and exists (select 1 from public.calibracao_execucoes e where e.id = execucao_id and e.organizacao_id = public.current_organizacao_id() and e.status not in ('fechada', 'cancelada'))
  and (
    padrao_id is null
    or exists (
      select 1 from public.calibracao_padroes p
      where p.id = calibracao_execucao_tabelas.padrao_id
        and p.organizacao_id = public.current_organizacao_id()
    )
  )
  and (
    padrao_tabela_id is null
    or exists (
      select 1 from public.calibracao_padrao_tabelas t
      where t.id = calibracao_execucao_tabelas.padrao_tabela_id
        and t.padrao_id = calibracao_execucao_tabelas.padrao_id
        and t.organizacao_id = public.current_organizacao_id()
    )
  )
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
);
drop policy if exists "calibracao_execucao_tabelas_delete_editavel" on public.calibracao_execucao_tabelas;
create policy "calibracao_execucao_tabelas_delete_editavel" on public.calibracao_execucao_tabelas
for delete to authenticated using (
  organizacao_id = public.current_organizacao_id()
  and exists (select 1 from public.calibracao_execucoes e where e.id = execucao_id and e.status not in ('fechada', 'cancelada'))
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
);

drop policy if exists "calibracao_execucao_pontos_select_mesma_organizacao" on public.calibracao_execucao_pontos;
create policy "calibracao_execucao_pontos_select_mesma_organizacao" on public.calibracao_execucao_pontos
for select to authenticated using (organizacao_id = public.current_organizacao_id());
drop policy if exists "calibracao_execucao_pontos_insert_editavel" on public.calibracao_execucao_pontos;
create policy "calibracao_execucao_pontos_insert_editavel" on public.calibracao_execucao_pontos
for insert to authenticated with check (
  organizacao_id = public.current_organizacao_id()
  and exists (
    select 1 from public.calibracao_execucao_tabelas t
    join public.calibracao_execucoes e on e.id = t.execucao_id
    where t.id = execucao_tabela_id and e.status not in ('fechada', 'cancelada')
  )
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
);
drop policy if exists "calibracao_execucao_pontos_update_editavel" on public.calibracao_execucao_pontos;
create policy "calibracao_execucao_pontos_update_editavel" on public.calibracao_execucao_pontos
for update to authenticated using (
  organizacao_id = public.current_organizacao_id()
  and exists (
    select 1 from public.calibracao_execucao_tabelas t
    join public.calibracao_execucoes e on e.id = t.execucao_id
    where t.id = execucao_tabela_id and e.status not in ('fechada', 'cancelada')
  )
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
) with check (
  organizacao_id = public.current_organizacao_id()
  and exists (
    select 1 from public.calibracao_execucao_tabelas t
    join public.calibracao_execucoes e on e.id = t.execucao_id
    where t.id = execucao_tabela_id and e.status not in ('fechada', 'cancelada')
  )
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
);
drop policy if exists "calibracao_execucao_pontos_delete_editavel" on public.calibracao_execucao_pontos;
create policy "calibracao_execucao_pontos_delete_editavel" on public.calibracao_execucao_pontos
for delete to authenticated using (
  organizacao_id = public.current_organizacao_id()
  and exists (
    select 1 from public.calibracao_execucao_tabelas t
    join public.calibracao_execucoes e on e.id = t.execucao_id
    where t.id = execucao_tabela_id and e.status not in ('fechada', 'cancelada')
  )
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
);

drop policy if exists "calibracao_execucao_leituras_select_mesma_organizacao" on public.calibracao_execucao_leituras;
create policy "calibracao_execucao_leituras_select_mesma_organizacao" on public.calibracao_execucao_leituras
for select to authenticated using (organizacao_id = public.current_organizacao_id());
drop policy if exists "calibracao_execucao_leituras_insert_editavel" on public.calibracao_execucao_leituras;
create policy "calibracao_execucao_leituras_insert_editavel" on public.calibracao_execucao_leituras
for insert to authenticated with check (
  organizacao_id = public.current_organizacao_id()
  and exists (
    select 1 from public.calibracao_execucao_pontos p
    join public.calibracao_execucao_tabelas t on t.id = p.execucao_tabela_id
    join public.calibracao_execucoes e on e.id = t.execucao_id
    where p.id = execucao_ponto_id and e.status not in ('fechada', 'cancelada')
  )
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
);
drop policy if exists "calibracao_execucao_leituras_delete_editavel" on public.calibracao_execucao_leituras;
create policy "calibracao_execucao_leituras_delete_editavel" on public.calibracao_execucao_leituras
for delete to authenticated using (
  organizacao_id = public.current_organizacao_id()
  and exists (
    select 1 from public.calibracao_execucao_pontos p
    join public.calibracao_execucao_tabelas t on t.id = p.execucao_tabela_id
    join public.calibracao_execucoes e on e.id = t.execucao_id
    where p.id = execucao_ponto_id and e.status not in ('fechada', 'cancelada')
  )
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
);

drop policy if exists "calibracao_execucao_componentes_select_mesma_organizacao" on public.calibracao_execucao_componentes_incerteza;
create policy "calibracao_execucao_componentes_select_mesma_organizacao" on public.calibracao_execucao_componentes_incerteza
for select to authenticated using (organizacao_id = public.current_organizacao_id());
drop policy if exists "calibracao_execucao_componentes_insert_editavel" on public.calibracao_execucao_componentes_incerteza;
create policy "calibracao_execucao_componentes_insert_editavel" on public.calibracao_execucao_componentes_incerteza
for insert to authenticated with check (
  organizacao_id = public.current_organizacao_id()
  and exists (
    select 1 from public.calibracao_execucao_pontos p
    join public.calibracao_execucao_tabelas t on t.id = p.execucao_tabela_id
    join public.calibracao_execucoes e on e.id = t.execucao_id
    where p.id = execucao_ponto_id and e.status not in ('fechada', 'cancelada')
  )
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
);
drop policy if exists "calibracao_execucao_componentes_delete_editavel" on public.calibracao_execucao_componentes_incerteza;
create policy "calibracao_execucao_componentes_delete_editavel" on public.calibracao_execucao_componentes_incerteza
for delete to authenticated using (
  organizacao_id = public.current_organizacao_id()
  and exists (
    select 1 from public.calibracao_execucao_pontos p
    join public.calibracao_execucao_tabelas t on t.id = p.execucao_tabela_id
    join public.calibracao_execucoes e on e.id = t.execucao_id
    where p.id = execucao_ponto_id and e.status not in ('fechada', 'cancelada')
  )
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
);

drop policy if exists "calibracao_certificados_storage_select_mesma_organizacao" on storage.objects;
create policy "calibracao_certificados_storage_select_mesma_organizacao" on storage.objects
for select to authenticated using (
  bucket_id = 'calibracao-certificados'
  and (storage.foldername(name))[1] = public.current_organizacao_id()::text
);
drop policy if exists "calibracao_certificados_storage_insert_admin_gestor_tecnico" on storage.objects;
create policy "calibracao_certificados_storage_insert_admin_gestor_tecnico" on storage.objects
for insert to authenticated with check (
  bucket_id = 'calibracao-certificados'
  and (storage.foldername(name))[1] = public.current_organizacao_id()::text
  and exists (
    select 1
    from public.calibracao_execucoes e
    where e.id::text = (storage.foldername(name))[2]
      and e.organizacao_id = public.current_organizacao_id()
      and e.status not in ('fechada', 'cancelada')
      and name = e.organizacao_id::text
        || '/'
        || e.id::text
        || '/CAL-'
        || lpad(e.numero_certificado::text, 6, '0')
        || '.pdf'
  )
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
);
drop policy if exists "calibracao_certificados_storage_update_admin_gestor_tecnico" on storage.objects;
drop policy if exists "calibracao_certificados_storage_delete_execucao_aberta" on storage.objects;
create policy "calibracao_certificados_storage_delete_execucao_aberta" on storage.objects
for delete to authenticated using (
  bucket_id = 'calibracao-certificados'
  and (storage.foldername(name))[1] = public.current_organizacao_id()::text
  and exists (
    select 1
    from public.calibracao_execucoes e
    where e.id::text = (storage.foldername(name))[2]
      and e.organizacao_id = public.current_organizacao_id()
      and e.status not in ('fechada', 'cancelada')
  )
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
);

create or replace function public.finalizar_calibracao_execucao(
  p_execucao_id uuid,
  p_pdf_storage_path text,
  p_pdf_hash text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_execucao public.calibracao_execucoes%rowtype;
  v_tipo_os_id uuid;
  v_estado_os_id uuid;
  v_os_id uuid;
  v_expected_pdf_storage_path text;
begin
  if coalesce(public.current_user_perfil(), '') not in ('admin', 'gestor', 'tecnico') then
    raise exception 'Usuario sem permissao para finalizar calibracao.';
  end if;

  select *
  into v_execucao
  from public.calibracao_execucoes
  where id = p_execucao_id
    and organizacao_id = public.current_organizacao_id()
  for update;

  if not found then
    raise exception 'Execucao de calibracao nao encontrada.';
  end if;

  if v_execucao.status in ('fechada', 'cancelada') then
    raise exception 'A calibracao fechada ou cancelada nao pode ser finalizada.';
  end if;

  if v_execucao.resultado_geral is null then
    raise exception 'Calcule o resultado geral antes de finalizar.';
  end if;

  if not exists (
    select 1
    from public.calibracao_execucao_tabelas t
    where t.execucao_id = v_execucao.id
  ) then
    raise exception 'A calibracao nao possui tabelas.';
  end if;

  if exists (
    select 1
    from public.calibracao_execucao_tabelas t
    where t.execucao_id = v_execucao.id
      and (
        t.padrao_id is null
        or t.padrao_tabela_id is null
        or t.padrao_validade_snapshot is null
        or t.padrao_validade_snapshot < v_execucao.data_calibracao
      )
  ) then
    raise exception 'Todas as tabelas devem possuir padrao valido na data da calibracao.';
  end if;

  if exists (
    select 1
    from public.calibracao_execucao_tabelas t
    where t.execucao_id = v_execucao.id
      and not exists (
        select 1
        from public.calibracao_execucao_pontos p
        where p.execucao_tabela_id = t.id
      )
  ) then
    raise exception 'Todas as tabelas devem possuir ao menos um ponto.';
  end if;

  if exists (
    select 1
    from public.calibracao_execucao_tabelas t
    join public.calibracao_execucao_pontos p on p.execucao_tabela_id = t.id
    where t.execucao_id = v_execucao.id
      and (
        p.incerteza_expandida is null
        or p.fator_abrangencia_k is null
        or (
          select count(*)
          from public.calibracao_execucao_leituras l
          where l.execucao_ponto_id = p.id
        ) <> t.quantidade_leituras_snapshot
      )
  ) then
    raise exception 'Todos os pontos devem possuir leituras e calculos completos.';
  end if;

  if v_execucao.criterio_conformidade_aplicado and exists (
    select 1
    from public.calibracao_execucao_tabelas t
    where t.execucao_id = v_execucao.id
      and not t.incluir_criterio_aceitacao_snapshot
  ) then
    raise exception 'Todas as tabelas devem possuir criterio para emitir declaracao de conformidade.';
  end if;

  if v_execucao.criterio_conformidade_aplicado and exists (
    select 1
    from public.calibracao_execucao_tabelas t
    join public.calibracao_execucao_pontos p on p.execucao_tabela_id = t.id
    where t.execucao_id = v_execucao.id
      and (
        p.resultado_conformidade is null
        or p.resultado_conformidade not in ('conforme', 'nao_conforme')
      )
  ) then
    raise exception 'Todos os pontos devem possuir avaliacao de conformidade.';
  end if;

  if (
    not v_execucao.criterio_conformidade_aplicado
    and v_execucao.resultado_geral <> 'sem_declaracao_conformidade'
  ) then
    raise exception 'Resultado geral invalido para calibracao sem declaracao de conformidade.';
  end if;

  if (
    v_execucao.criterio_conformidade_aplicado
    and v_execucao.resultado_geral not in ('conforme', 'nao_conforme')
  ) then
    raise exception 'Resultado geral invalido para calibracao com declaracao de conformidade.';
  end if;

  if (
    v_execucao.criterio_conformidade_aplicado
    and v_execucao.resultado_geral = 'conforme'
    and exists (
      select 1
      from public.calibracao_execucao_tabelas t
      join public.calibracao_execucao_pontos p on p.execucao_tabela_id = t.id
      where t.execucao_id = v_execucao.id
        and p.resultado_conformidade <> 'conforme'
    )
  ) then
    raise exception 'Resultado geral inconsistente com os resultados dos pontos.';
  end if;

  if (
    v_execucao.criterio_conformidade_aplicado
    and v_execucao.resultado_geral = 'nao_conforme'
    and not exists (
      select 1
      from public.calibracao_execucao_tabelas t
      join public.calibracao_execucao_pontos p on p.execucao_tabela_id = t.id
      where t.execucao_id = v_execucao.id
        and p.resultado_conformidade = 'nao_conforme'
    )
  ) then
    raise exception 'Resultado geral inconsistente com os resultados dos pontos.';
  end if;

  v_expected_pdf_storage_path :=
    v_execucao.organizacao_id::text
    || '/'
    || v_execucao.id::text
    || '/CAL-'
    || lpad(v_execucao.numero_certificado::text, 6, '0')
    || '.pdf';

  if p_pdf_storage_path is distinct from v_expected_pdf_storage_path then
    raise exception 'Caminho do certificado PDF invalido.';
  end if;

  if p_pdf_hash is null or p_pdf_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'Hash SHA-256 do certificado PDF invalido.';
  end if;

  if not exists (
    select 1
    from storage.objects o
    where o.bucket_id = 'calibracao-certificados'
      and o.name = p_pdf_storage_path
  ) then
    raise exception 'Certificado PDF nao encontrado no storage.';
  end if;

  select id into v_tipo_os_id
  from public.tipos_os
  where organizacao_id = v_execucao.organizacao_id
    and ativo
    and lower(nome) = lower('Calibração')
  limit 1;

  select id into v_estado_os_id
  from public.estados_os
  where organizacao_id = v_execucao.organizacao_id
    and ativo
    and finaliza_os
  order by ordem desc
  limit 1;

  if v_tipo_os_id is null then
    raise exception 'Cadastre um tipo de OS ativo chamado Calibracao antes de finalizar.';
  end if;

  if v_estado_os_id is null then
    raise exception 'Cadastre um estado final ativo de OS antes de finalizar.';
  end if;

  insert into public.ordens_servico (
    organizacao_id,
    empresa_id,
    equipamento_id,
    tipo_os_id,
    estado_os_id,
    solicitante_texto,
    responsavel_texto,
    data_abertura,
    data_fechamento,
    descricao_servico,
    observacoes,
    prioridade,
    status_sistema,
    ativo
  )
  values (
    v_execucao.organizacao_id,
    v_execucao.empresa_id,
    v_execucao.equipamento_id,
    v_tipo_os_id,
    v_estado_os_id,
    v_execucao.responsavel_solicitante,
    v_execucao.responsavel_tecnico_nome,
    now(),
    now(),
    'Calibração executada. Certificado CAL-' || lpad(v_execucao.numero_certificado::text, 6, '0') || '.',
    v_execucao.observacoes,
    'normal',
    'fechada',
    true
  )
  returning id into v_os_id;

  insert into public.ordem_servico_historico (
    ordem_servico_id,
    estado_novo_id,
    acao,
    observacao
  )
  values (
    v_os_id,
    v_estado_os_id,
    'criada_calibracao',
    'Ordem de Serviço fechada gerada automaticamente pela calibração.'
  );

  update public.calibracao_execucoes
  set
    os_id = v_os_id,
    pdf_storage_path = p_pdf_storage_path,
    pdf_hash = p_pdf_hash,
    status = 'fechada',
    fechado_em = now()
  where id = p_execucao_id;

  update public.equipamentos
  set
    data_ultima_calibracao = v_execucao.data_calibracao,
    data_proxima_calibracao = v_execucao.data_validade
  where id = v_execucao.equipamento_id
    and organizacao_id = v_execucao.organizacao_id;

  return v_os_id;
end;
$$;

alter function public.finalizar_calibracao_execucao(uuid, text, text) owner to postgres;
revoke all on function public.finalizar_calibracao_execucao(uuid, text, text) from public;
grant execute on function public.finalizar_calibracao_execucao(uuid, text, text) to authenticated;

-- ============================================================
-- Fim da migration 024_calibracao_execucoes.sql
-- ============================================================
