-- ============================================================
-- EngClinica Pro
-- Migration: 037_seguranca_eletrica.sql
-- Objetivo:
-- - Criar execucoes e resultados de ensaio de seguranca eletrica
-- - Reutilizar padroes cadastrados na aba de calibracao
-- ============================================================

create table if not exists public.seguranca_eletrica_execucoes (
  id uuid primary key default gen_random_uuid(),
  organizacao_id uuid not null references public.organizacoes(id) on delete restrict,
  numero_certificado bigint generated by default as identity unique,
  empresa_id uuid not null references public.empresas(id) on delete restrict,
  equipamento_id uuid not null references public.equipamentos(id) on delete restrict,
  padrao_id uuid null references public.calibracao_padroes(id) on delete set null,
  classe_equipamento text not null default 'Classe I',
  tipo_parte_aplicada text not null default 'Tipo BF',
  temperatura_ambiente_texto text null default '21 a 25',
  umidade_relativa_texto text null default '45 a 75',
  local_ensaio text null,
  data_teste date not null,
  data_emissao date not null default current_date,
  data_validade date null,
  tecnico_executor_nome text not null,
  responsavel_tecnico_nome text not null,
  responsavel_solicitante text null,
  resultado_geral text not null default 'aprovado',
  observacoes text null,
  status text not null default 'fechada',
  ativo boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  created_by uuid null references public.usuarios(id) on delete set null,
  updated_by uuid null references public.usuarios(id) on delete set null,
  constraint seguranca_eletrica_execucoes_status_check
    check (status in ('rascunho', 'fechada', 'cancelada')),
  constraint seguranca_eletrica_execucoes_resultado_check
    check (resultado_geral in ('aprovado', 'reprovado')),
  constraint seguranca_eletrica_execucoes_datas_check
    check (data_validade is null or data_validade >= data_teste)
);

create table if not exists public.seguranca_eletrica_resultados (
  id uuid primary key default gen_random_uuid(),
  organizacao_id uuid not null references public.organizacoes(id) on delete restrict,
  execucao_id uuid not null references public.seguranca_eletrica_execucoes(id) on delete cascade,
  grupo text not null,
  caracteristica text not null,
  unidade text not null,
  valor_esperado_texto text not null,
  valor_esperado_numero numeric(18,8) null,
  operador_limite text null,
  valor_registrado numeric(18,8) null,
  valor_registrado_texto text null,
  desvio numeric(18,8) null,
  desvio_texto text null,
  resultado text not null default 'n/a',
  ordem integer not null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint seguranca_eletrica_resultados_resultado_check
    check (resultado in ('aprovado', 'reprovado', 'n/a'))
);

create index if not exists idx_seguranca_eletrica_execucoes_organizacao
on public.seguranca_eletrica_execucoes (organizacao_id);

create index if not exists idx_seguranca_eletrica_execucoes_empresa
on public.seguranca_eletrica_execucoes (empresa_id);

create index if not exists idx_seguranca_eletrica_execucoes_equipamento
on public.seguranca_eletrica_execucoes (equipamento_id);

create index if not exists idx_seguranca_eletrica_execucoes_padrao
on public.seguranca_eletrica_execucoes (padrao_id);

create index if not exists idx_seguranca_eletrica_execucoes_data
on public.seguranca_eletrica_execucoes (data_teste);

create index if not exists idx_seguranca_eletrica_resultados_execucao
on public.seguranca_eletrica_resultados (execucao_id);

drop trigger if exists trg_seguranca_eletrica_execucoes_updated_at on public.seguranca_eletrica_execucoes;
create trigger trg_seguranca_eletrica_execucoes_updated_at
before update on public.seguranca_eletrica_execucoes
for each row execute function public.set_updated_at();

drop trigger if exists trg_seguranca_eletrica_resultados_updated_at on public.seguranca_eletrica_resultados;
create trigger trg_seguranca_eletrica_resultados_updated_at
before update on public.seguranca_eletrica_resultados
for each row execute function public.set_updated_at();

alter table public.seguranca_eletrica_execucoes enable row level security;
alter table public.seguranca_eletrica_resultados enable row level security;

drop policy if exists "seguranca_eletrica_execucoes_select_mesma_organizacao" on public.seguranca_eletrica_execucoes;
create policy "seguranca_eletrica_execucoes_select_mesma_organizacao"
on public.seguranca_eletrica_execucoes
for select to authenticated
using (organizacao_id = public.current_organizacao_id());

drop policy if exists "seguranca_eletrica_execucoes_insert_admin_gestor_tecnico" on public.seguranca_eletrica_execucoes;
create policy "seguranca_eletrica_execucoes_insert_admin_gestor_tecnico"
on public.seguranca_eletrica_execucoes
for insert to authenticated
with check (
  organizacao_id = public.current_organizacao_id()
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
  and exists (
    select 1 from public.empresas e
    where e.id = seguranca_eletrica_execucoes.empresa_id
      and e.organizacao_id = public.current_organizacao_id()
  )
  and exists (
    select 1 from public.equipamentos e
    where e.id = seguranca_eletrica_execucoes.equipamento_id
      and e.empresa_id = seguranca_eletrica_execucoes.empresa_id
      and e.organizacao_id = public.current_organizacao_id()
  )
  and (
    padrao_id is null
    or exists (
      select 1 from public.calibracao_padroes p
      where p.id = seguranca_eletrica_execucoes.padrao_id
        and p.organizacao_id = public.current_organizacao_id()
    )
  )
);

drop policy if exists "seguranca_eletrica_execucoes_update_admin_gestor_tecnico" on public.seguranca_eletrica_execucoes;
create policy "seguranca_eletrica_execucoes_update_admin_gestor_tecnico"
on public.seguranca_eletrica_execucoes
for update to authenticated
using (
  organizacao_id = public.current_organizacao_id()
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
)
with check (
  organizacao_id = public.current_organizacao_id()
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
);

drop policy if exists "seguranca_eletrica_resultados_select_mesma_organizacao" on public.seguranca_eletrica_resultados;
create policy "seguranca_eletrica_resultados_select_mesma_organizacao"
on public.seguranca_eletrica_resultados
for select to authenticated
using (organizacao_id = public.current_organizacao_id());

drop policy if exists "seguranca_eletrica_resultados_insert_mesma_organizacao" on public.seguranca_eletrica_resultados;
create policy "seguranca_eletrica_resultados_insert_mesma_organizacao"
on public.seguranca_eletrica_resultados
for insert to authenticated
with check (
  organizacao_id = public.current_organizacao_id()
  and exists (
    select 1 from public.seguranca_eletrica_execucoes e
    where e.id = seguranca_eletrica_resultados.execucao_id
      and e.organizacao_id = public.current_organizacao_id()
  )
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
);

drop policy if exists "seguranca_eletrica_resultados_delete_mesma_organizacao" on public.seguranca_eletrica_resultados;
create policy "seguranca_eletrica_resultados_delete_mesma_organizacao"
on public.seguranca_eletrica_resultados
for delete to authenticated
using (
  organizacao_id = public.current_organizacao_id()
  and public.current_user_perfil() in ('admin', 'gestor', 'tecnico')
);

notify pgrst, 'reload schema';

-- Fim da migration 037_seguranca_eletrica.sql
