-- ============================================================
-- Ipromed - Sistema de Gestao
-- Migration: 055_utilitarios_termos_locacao.sql
-- Objetivo:
-- - Criar o modulo Utilitarios
-- - Registrar termos de locacao/emprestimo de equipamentos
-- - Controlar mensalidades de termos com valor mensal
-- ============================================================

insert into public.permissoes (chave, nome, grupo, descricao, ordem, ativo)
values
  ('utilitarios.visualizar', 'Visualizar utilitarios', 'Utilitarios', 'Consultar utilitarios e termos emitidos.', 280, true),
  ('utilitarios.gerenciar', 'Gerenciar utilitarios', 'Utilitarios', 'Criar e editar termos de locacao e emprestimo.', 290, true)
on conflict (chave) do update set
  nome = excluded.nome,
  grupo = excluded.grupo,
  descricao = excluded.descricao,
  ordem = excluded.ordem,
  ativo = excluded.ativo,
  updated_at = now();

insert into public.perfil_permissoes (organizacao_id, perfil, permissao_chave, permitido)
select
  o.id,
  perfil.nome,
  p.chave,
  case
    when perfil.nome in ('gestor', 'comercial') then true
    when perfil.nome = 'tecnico' then p.chave = 'utilitarios.visualizar'
    else false
  end
from public.organizacoes o
cross join (values ('gestor'), ('tecnico'), ('comercial'), ('solicitante')) as perfil(nome)
join public.permissoes p on p.chave in ('utilitarios.visualizar', 'utilitarios.gerenciar')
on conflict (organizacao_id, perfil, permissao_chave) do update set
  permitido = excluded.permitido,
  updated_at = now();

create table if not exists public.utilitario_termos_locacao (
  id uuid primary key default gen_random_uuid(),
  organizacao_id uuid not null references public.organizacoes(id) on delete restrict,
  numero bigint generated by default as identity,

  tipo text not null default 'locacao',
  modalidade_cobranca text not null default 'valor_unico',
  status text not null default 'ativo',

  empresa_locadora_id uuid null references public.empresas(id) on delete set null,
  empresa_locataria_id uuid not null references public.empresas(id) on delete restrict,
  equipamento_id uuid not null references public.equipamentos(id) on delete restrict,

  responsavel_entrega text null,
  responsavel_recebimento text null,
  local_entrega text null,
  data_inicio date not null default current_date,
  data_prevista_devolucao date null,
  data_devolucao date null,

  valor_unico numeric(12,2) null,
  valor_mensal numeric(12,2) null,
  dia_vencimento integer null,
  observacoes text null,

  ativo boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  created_by uuid null references public.usuarios(id) on delete set null,
  updated_by uuid null references public.usuarios(id) on delete set null,

  constraint utilitario_termos_locacao_tipo_check
    check (tipo in ('locacao', 'emprestimo')),

  constraint utilitario_termos_locacao_modalidade_check
    check (modalidade_cobranca in ('valor_unico', 'valor_mensal')),

  constraint utilitario_termos_locacao_status_check
    check (status in ('ativo', 'encerrado', 'cancelado')),

  constraint utilitario_termos_locacao_valores_check
    check (
      (modalidade_cobranca = 'valor_unico' and coalesce(valor_unico, 0) >= 0)
      or
      (modalidade_cobranca = 'valor_mensal' and coalesce(valor_mensal, 0) >= 0)
    ),

  constraint utilitario_termos_locacao_dia_vencimento_check
    check (dia_vencimento is null or dia_vencimento between 1 and 31),

  constraint utilitario_termos_locacao_devolucao_check
    check (data_devolucao is null or data_devolucao >= data_inicio)
);

create table if not exists public.utilitario_termo_mensalidades (
  id uuid primary key default gen_random_uuid(),
  organizacao_id uuid not null references public.organizacoes(id) on delete restrict,
  termo_id uuid not null references public.utilitario_termos_locacao(id) on delete cascade,
  numero_parcela integer not null,
  data_vencimento date not null,
  valor numeric(12,2) not null default 0,
  pago boolean not null default false,
  data_pagamento date null,
  observacoes text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  created_by uuid null references public.usuarios(id) on delete set null,
  updated_by uuid null references public.usuarios(id) on delete set null,

  constraint utilitario_termo_mensalidades_numero_check check (numero_parcela > 0),
  constraint utilitario_termo_mensalidades_valor_check check (valor >= 0),
  constraint utilitario_termo_mensalidades_pagamento_check check (
    (pago and data_pagamento is not null)
    or
    (not pago)
  )
);

create unique index if not exists idx_utilitario_termos_locacao_numero
on public.utilitario_termos_locacao (numero);

create index if not exists idx_utilitario_termos_locacao_organizacao
on public.utilitario_termos_locacao (organizacao_id, created_at desc);

create index if not exists idx_utilitario_termos_locacao_cliente
on public.utilitario_termos_locacao (organizacao_id, empresa_locataria_id);

create index if not exists idx_utilitario_termos_locacao_equipamento
on public.utilitario_termos_locacao (organizacao_id, equipamento_id);

create unique index if not exists idx_utilitario_termos_locacao_equipamento_ativo
on public.utilitario_termos_locacao (organizacao_id, equipamento_id)
where ativo and status = 'ativo';

create unique index if not exists idx_utilitario_termo_mensalidades_parcela
on public.utilitario_termo_mensalidades (termo_id, numero_parcela);

create index if not exists idx_utilitario_termo_mensalidades_vencimento
on public.utilitario_termo_mensalidades (organizacao_id, data_vencimento);

drop trigger if exists trg_utilitario_termos_locacao_updated_at on public.utilitario_termos_locacao;
create trigger trg_utilitario_termos_locacao_updated_at
before update on public.utilitario_termos_locacao
for each row execute function public.set_updated_at();

drop trigger if exists trg_utilitario_termo_mensalidades_updated_at on public.utilitario_termo_mensalidades;
create trigger trg_utilitario_termo_mensalidades_updated_at
before update on public.utilitario_termo_mensalidades
for each row execute function public.set_updated_at();

alter table public.utilitario_termos_locacao enable row level security;
alter table public.utilitario_termo_mensalidades enable row level security;

drop policy if exists "utilitario_termos_locacao_select_por_permissao" on public.utilitario_termos_locacao;
create policy "utilitario_termos_locacao_select_por_permissao"
on public.utilitario_termos_locacao
for select
to authenticated
using (
  organizacao_id = public.current_organizacao_id()
  and public.user_has_permission('utilitarios.visualizar')
);

drop policy if exists "utilitario_termos_locacao_insert_por_permissao" on public.utilitario_termos_locacao;
create policy "utilitario_termos_locacao_insert_por_permissao"
on public.utilitario_termos_locacao
for insert
to authenticated
with check (
  organizacao_id = public.current_organizacao_id()
  and public.user_has_permission('utilitarios.gerenciar')
);

drop policy if exists "utilitario_termos_locacao_update_por_permissao" on public.utilitario_termos_locacao;
create policy "utilitario_termos_locacao_update_por_permissao"
on public.utilitario_termos_locacao
for update
to authenticated
using (
  organizacao_id = public.current_organizacao_id()
  and public.user_has_permission('utilitarios.gerenciar')
)
with check (
  organizacao_id = public.current_organizacao_id()
  and public.user_has_permission('utilitarios.gerenciar')
);

drop policy if exists "utilitario_termo_mensalidades_select_por_permissao" on public.utilitario_termo_mensalidades;
create policy "utilitario_termo_mensalidades_select_por_permissao"
on public.utilitario_termo_mensalidades
for select
to authenticated
using (
  organizacao_id = public.current_organizacao_id()
  and public.user_has_permission('utilitarios.visualizar')
);

drop policy if exists "utilitario_termo_mensalidades_insert_por_permissao" on public.utilitario_termo_mensalidades;
create policy "utilitario_termo_mensalidades_insert_por_permissao"
on public.utilitario_termo_mensalidades
for insert
to authenticated
with check (
  organizacao_id = public.current_organizacao_id()
  and public.user_has_permission('utilitarios.gerenciar')
);

drop policy if exists "utilitario_termo_mensalidades_update_por_permissao" on public.utilitario_termo_mensalidades;
create policy "utilitario_termo_mensalidades_update_por_permissao"
on public.utilitario_termo_mensalidades
for update
to authenticated
using (
  organizacao_id = public.current_organizacao_id()
  and public.user_has_permission('utilitarios.gerenciar')
)
with check (
  organizacao_id = public.current_organizacao_id()
  and public.user_has_permission('utilitarios.gerenciar')
);

notify pgrst, 'reload schema';

-- Fim da migration 055_utilitarios_termos_locacao.sql
