-- ============================================================
-- Ipromed - Sistema de Gestao
-- Migration: 063_utilitarios_recibos.sql
-- Objetivo:
-- - Criar gerador de recibos em Utilitarios
-- - Vincular recibos opcionalmente a OS e orcamentos
-- - Manter historico e auditoria dos recibos emitidos
-- ============================================================

create table if not exists public.utilitario_recibos (
  id uuid primary key default gen_random_uuid(),
  organizacao_id uuid not null references public.organizacoes(id) on delete restrict,
  numero bigint generated by default as identity,

  empresa_id uuid not null references public.empresas(id) on delete restrict,
  equipamento_id uuid not null references public.equipamentos(id) on delete restrict,
  ordem_servico_id uuid null references public.ordens_servico(id) on delete set null,
  orcamento_id uuid null references public.orcamentos(id) on delete set null,

  data_recibo date not null default current_date,
  valor numeric(12,2) not null,
  forma_pagamento text null,
  recebido_de text null,
  referente text not null,
  observacoes text null,

  ativo boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  created_by uuid null references public.usuarios(id) on delete set null,
  updated_by uuid null references public.usuarios(id) on delete set null,

  constraint utilitario_recibos_valor_check check (valor > 0)
);

create unique index if not exists idx_utilitario_recibos_numero
on public.utilitario_recibos (numero);

create index if not exists idx_utilitario_recibos_organizacao
on public.utilitario_recibos (organizacao_id, created_at desc);

create index if not exists idx_utilitario_recibos_empresa
on public.utilitario_recibos (organizacao_id, empresa_id);

create index if not exists idx_utilitario_recibos_equipamento
on public.utilitario_recibos (organizacao_id, equipamento_id);

create index if not exists idx_utilitario_recibos_os
on public.utilitario_recibos (organizacao_id, ordem_servico_id)
where ordem_servico_id is not null;

create index if not exists idx_utilitario_recibos_orcamento
on public.utilitario_recibos (organizacao_id, orcamento_id)
where orcamento_id is not null;

drop trigger if exists trg_utilitario_recibos_updated_at on public.utilitario_recibos;
create trigger trg_utilitario_recibos_updated_at
before update on public.utilitario_recibos
for each row execute function public.set_updated_at();

alter table public.utilitario_recibos enable row level security;

drop policy if exists "utilitario_recibos_select_por_permissao" on public.utilitario_recibos;
create policy "utilitario_recibos_select_por_permissao"
on public.utilitario_recibos
for select
to authenticated
using (
  organizacao_id = public.current_organizacao_id()
  and public.user_has_permission('utilitarios.visualizar')
);

drop policy if exists "utilitario_recibos_insert_por_permissao" on public.utilitario_recibos;
create policy "utilitario_recibos_insert_por_permissao"
on public.utilitario_recibos
for insert
to authenticated
with check (
  organizacao_id = public.current_organizacao_id()
  and public.user_has_permission('utilitarios.gerenciar')
);

drop policy if exists "utilitario_recibos_update_por_permissao" on public.utilitario_recibos;
create policy "utilitario_recibos_update_por_permissao"
on public.utilitario_recibos
for update
to authenticated
using (
  organizacao_id = public.current_organizacao_id()
  and public.user_has_permission('utilitarios.gerenciar')
)
with check (
  organizacao_id = public.current_organizacao_id()
  and public.user_has_permission('utilitarios.gerenciar')
);

do $$
begin
  if to_regclass('public.utilitario_recibos') is not null
     and to_regclass('public.auditoria_logs') is not null then
    drop trigger if exists trg_auditoria_utilitario_recibos on public.utilitario_recibos;
    create trigger trg_auditoria_utilitario_recibos
    after insert or update or delete on public.utilitario_recibos
    for each row execute function public.auditoria_registrar_alteracao('Utilitarios');
  end if;
end $$;

notify pgrst, 'reload schema';

-- Fim da migration 063_utilitarios_recibos.sql
